#设置端口号
server:
  port: 10200  #自己设置的端口号
#注册中心设置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #注册中心的地址  在注册中心里面找
spring:
  application:
    name: fengconsumer #唯一名称
